[package]
name = "stable-swap"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
escrow = "0x0"
fungible_tokens = "0x0"
benzo = "0x2"
blaze = "0x3"
candy_yul = "0x4"
